################################################
#
# Default config file. Is read on startup
# and overrides default settings. 
#
# Any command line arguments override settings
# loaded from this config file.
#
###############################################


#universalsetsize = 90
#ssetsize = 10
#tsetsize = 40

# >=0 : this values will be used
# -1 : the theoretically calculated value will be used as expected reference value 
#      (the default)
# any other value < 0: no reference expected value will be used
# targetexpectedjaccardsimilarity = 0.0334

displayconfigorigin = False
autoterminate= True
savesimilarities = False
jaccardmode = sklearn

outputcsvfile = output/jaccardSimilarities

plotheight = 780
plotwidth = 1700

# How to set lists in config file. 
# e.g. which additional aspects to log
# fields-list=[tset, sset]
